version: 18
jobs:
- name: ☁️同步
  steps:
  - !PushRepository
    name: Sync
    remoteUrl: https://github.com/20020314/x-ui
    userName: '20020314'
    passwordSecret: Token
    withLfs: false
    force: true
    condition: ALWAYS
  triggers:
  - !BranchUpdateTrigger {}
  - !TagCreateTrigger {}
  - !PullRequestUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
